# Generated by Django 3.2.9 on 2021-11-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211112_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=255)),
                ('uemail', models.CharField(max_length=255)),
                ('ucontact', models.CharField(max_length=50)),
                ('password', models.CharField(default='SOME STRING', max_length=30)),
                ('repassword', models.CharField(default='SOME STRING', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='repassword',
        ),
    ]
