# Generated by Django 3.2.9 on 2021-11-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ucontact',
        ),
    ]
