# Generated by Django 3.2.9 on 2021-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_user_uemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
