# Generated by Django 3.2.9 on 2021-11-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_user_uemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='SOME INT', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='repassword',
            field=models.CharField(default='SOME INT', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(max_length=255),
        ),
    ]
