# Generated by Django 3.2.9 on 2021-11-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20211122_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
